name: Autograding Tests
'on':
- push
- repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: swapInt
      id: swapint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: swapInt
        setup-command: ''
        command: make test try=swapInt
        timeout: 10
        max-score: 10

    - name: bubblePass
      id: bubblepass
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: bubblePass
        setup-command: ''
        command: make test try=bubblePass
        timeout: 10
        max-score: 15

    - name: bubbleSort
      id: bubblesort
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: bubbleSort
        setup-command: ''
        command: make test try=bubbleSort
        timeout: 10
        max-score: 10

    - name: insertionStep
      id: insertionstep
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: insertionStep
        setup-command: ''
        command: make test try=insertionStep
        timeout: 10
        max-score: 15

    - name: insertionSort
      id: insertionsort
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: insertionSort
        setup-command: ''
        command: make test try=insertionSort
        timeout: 10
        max-score: 10

    - name: swap
      id: swap
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: swap
        setup-command: ''
        command: make test try=swap
        timeout: 10
        max-score: 10

    - name: minFind
      id: minfind
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: minFind
        setup-command: ''
        command: make test try=minFind
        timeout: 10
        max-score: 10

    - name: newSort
      id: newsort
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: newSort
        setup-command: ''
        command: make test try=newSort
        timeout: 10
        max-score: 20

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SWAPINT_RESULTS: "${{steps.swapint.outputs.result}}"
        BUBBLEPASS_RESULTS: "${{steps.bubblepass.outputs.result}}"
        BUBBLESORT_RESULTS: "${{steps.bubblesort.outputs.result}}"
        INSERTIONSTEP_RESULTS: "${{steps.insertionstep.outputs.result}}"
        INSERTIONSORT_RESULTS: "${{steps.insertionsort.outputs.result}}"
        SWAP_RESULTS: "${{steps.swap.outputs.result}}"
        MINFIND_RESULTS: "${{steps.minfind.outputs.result}}"
        NEWSORT_RESULTS: "${{steps.newsort.outputs.result}}"
      with:
        runners: swapint,bubblepass,bubblesort,insertionstep,insertionsort,swap,minfind,newsort